Repository census-instrumentation/opencensus-node, pull requests merged in 2018-11, with the labels that each got.

#168 Use setInterval to upload metrics to Stackdriver periodically
  packages/opencensus-exporter-stackdriver/src/stackdriver-monitoring.ts
  packages/opencensus-exporter-stackdriver/src/types.ts
  packages/opencensus-exporter-stackdriver/test/test-stackdriver-monitoring.ts
Labels: cla: yes, exporters

#162 fix spanId format
  package-lock.json
  packages/opencensus-core/package-lock.json
  packages/opencensus-exporter-stackdriver/package-lock.json
  packages/opencensus-exporter-stackdriver/package.json
  packages/opencensus-exporter-stackdriver/src/modules.d.ts
  packages/opencensus-exporter-stackdriver/src/stackdriver-cloudtrace.ts
  packages/opencensus-exporter-stackdriver/test/test-stackdriver-cloudtrace.ts
Labels: cla: yes

#175 Drops negative bucket bounds and negative values in record API
  packages/opencensus-core/src/stats/stats.ts
  packages/opencensus-core/src/stats/view.ts
  packages/opencensus-core/test/test-stats.ts
  packages/opencensus-core/test/test-view.ts
Labels: cla: yes

#184 Disables broken test with newest gcloud
  lerna.json
  package-lock.json
  package.json
  packages/opencensus-exporter-stackdriver/package-lock.json
  packages/opencensus-exporter-stackdriver/test/test-stackdriver-cloudtrace.ts
  packages/opencensus-exporter-stackdriver/test/test-stackdriver-monitoring.ts
Labels: cla: yes

#185 Rename prefix name for [StackdriverStatsExporter]
  package-lock.json
  packages/opencensus-core/package-lock.json
  packages/opencensus-exporter-instana/package-lock.json
  packages/opencensus-exporter-jaeger/package-lock.json
  packages/opencensus-exporter-ocagent/package-lock.json
  packages/opencensus-exporter-stackdriver/package-lock.json
  packages/opencensus-exporter-stackdriver/src/modules.d.ts
  packages/opencensus-exporter-stackdriver/src/stackdriver-cloudtrace.ts
  packages/opencensus-exporter-stackdriver/src/stackdriver-monitoring.ts
  packages/opencensus-exporter-stackdriver/src/types.ts
  packages/opencensus-exporter-stackdriver/test/test-stackdriver-cloudtrace.ts
  packages/opencensus-exporter-stackdriver/test/test-stackdriver-monitoring.ts
  packages/opencensus-exporter-zipkin/package-lock.json
  packages/opencensus-exporter-zpages/package-lock.json
  packages/opencensus-instrumentation-grpc/package-lock.json
  packages/opencensus-instrumentation-http/package-lock.json
  packages/opencensus-instrumentation-http2/package-lock.json
  packages/opencensus-instrumentation-https/package-lock.json
  packages/opencensus-instrumentation-mongodb/package-lock.json
  packages/opencensus-nodejs/package-lock.json
  packages/opencensus-propagation-b3/package-lock.json
  packages/opencensus-propagation-jaeger/package-lock.json
  packages/opencensus-propagation-stackdriver/package-lock.json
  packages/opencensus-propagation-tracecontext/package-lock.json
Labels: cla: yes

#186 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: cla: yes

#189 Adds contributing document
  CONTRIBUTING.md
Labels: cla: yes

#191 Adds metric utils to convert Stats data models to Metric data models
  packages/opencensus-core/src/index.ts
  packages/opencensus-core/src/metrics/export/types.ts
  packages/opencensus-core/src/stats/metric-utils.ts
  packages/opencensus-core/test/test-metric-utils.ts
Labels: cla: yes

#169 instrumentation-http: Parse URL instead of relying on pathname
  package-lock.json
  packages/opencensus-instrumentation-http/src/http.ts
Labels: cla: yes

#195 Fix Metric: LabelValue
  package-lock.json
  packages/opencensus-core/src/metrics/export/types.ts
  packages/opencensus-core/src/stats/metric-utils.ts
  packages/opencensus-core/test/test-metric-utils.ts
Labels: cla: yes

#197 Exporter/Stats/Stackdriver: Fix MetricDescriptors ValueType
  packages/opencensus-exporter-stackdriver/src/types.ts
  packages/opencensus-exporter-stackdriver/test/test-stackdriver-monitoring.ts
Labels: cla: yes

#135 Fix up typos in source
  packages/opencensus-exporter-jaeger/src/jaeger-driver/index.ts
  packages/opencensus-exporter-jaeger/src/jaeger.ts
  packages/opencensus-exporter-jaeger/test/test-jaeger.ts
  packages/opencensus-exporter-prometheus/src/prometheus-stats.ts
  packages/opencensus-nodejs/src/trace/config/default-config.ts
  packages/opencensus-nodejs/src/trace/constants.ts
  packages/opencensus-nodejs/src/trace/tracing.ts
Labels: cla: yes

#131 Export package version
  packages/opencensus-core/src/common/version.ts
  packages/opencensus-core/src/index.ts
  packages/opencensus-exporter-ocagent/src/ocagent.ts
Labels: cla: yes

#198 Performance: Use one 24 byte random buffer instead of calling randomBytes() twice
  packages/opencensus-propagation-tracecontext/src/tracecontext-format.ts
Labels: cla: yes

#200 Enforce "noUnusedLocals" : Report errors on unused locals.
  packages/opencensus-core/src/exporters/console-exporter.ts
  packages/opencensus-core/src/exporters/exporter-buffer.ts
  packages/opencensus-core/src/stats/view.ts
  packages/opencensus-core/src/trace/instrumentation/base-plugin.ts
  packages/opencensus-core/src/trace/model/root-span.ts
  packages/opencensus-core/src/trace/model/span-base.ts
  packages/opencensus-core/src/trace/model/tracer.ts
  packages/opencensus-core/src/trace/sampler/sampler.ts
  packages/opencensus-core/src/trace/types.ts
  packages/opencensus-core/test/test-console-exporter.ts
  packages/opencensus-core/test/test-console-logger.ts
  packages/opencensus-core/test/test-exporter-buffer.ts
  packages/opencensus-core/test/test-recorder.ts
  packages/opencensus-core/test/test-root-span.ts
  packages/opencensus-core/test/test-sampler.ts
  packages/opencensus-core/test/test-span.ts
  packages/opencensus-core/test/test-stats.ts
  packages/opencensus-core/test/test-tracer.ts
  packages/opencensus-core/test/test-view.ts
  packages/opencensus-core/tsconfig.json
Labels: cla: yes, enhancement

#202 Add CHANGELOG.md
  CHANGELOG.md
Labels: cla: yes

#193 Add Resource API
  packages/opencensus-core/src/internal/string-utils.ts
  packages/opencensus-core/src/resource/resource.ts
  packages/opencensus-core/src/resource/types.ts
  packages/opencensus-core/test/test-resource.ts
  packages/opencensus-core/test/test-string-utils.ts
Labels: Resource, cla: yes

#203 Add metric registry and validations util
  packages/opencensus-core/src/common/validations.ts
  packages/opencensus-core/src/metrics/metric-registry.ts
  packages/opencensus-core/test/test-metric-registry.ts
Labels: API, Metrics, cla: yes

#209 Renames DistributionData[sumSquaredDeviations] to [sumOfSquaredDeviation]
  packages/opencensus-core/src/stats/recorder.ts
  packages/opencensus-core/src/stats/types.ts
  packages/opencensus-core/src/stats/view.ts
  packages/opencensus-core/test/test-recorder.ts
  packages/opencensus-core/test/test-view.ts
  packages/opencensus-exporter-stackdriver/src/stackdriver-monitoring.ts
  packages/opencensus-exporter-zpages/templates/statsz-view-distribution.ejs
  packages/opencensus-exporter-zpages/test/test-zpages.ts
Labels: cla: yes

#208 Drops whole measurement list if some of value is negative
  packages/opencensus-core/src/stats/stats.ts
  packages/opencensus-core/test/test-stats.ts
Labels: cla: yes
