Repository census-instrumentation/opencensus-node, pull requests merged in 2019-05, with the labels that each got.

#488 Move propagation-binaryformat package to dependencies.
  packages/opencensus-instrumentation-grpc/package.json
Labels: cla: yes

#484 feat(tracer): separate cls from tracer
  CHANGELOG.md
  examples/grpc/capitalize_server.js
  examples/http/server.js
  examples/trace/multi-span-tracing.js
  packages/opencensus-core/src/index.ts
  packages/opencensus-core/src/trace/instrumentation/types.ts
  packages/opencensus-core/src/trace/model/no-record/no-record-root-span.ts
  packages/opencensus-core/src/trace/model/root-span.ts
  packages/opencensus-core/src/trace/model/tracer-base.ts
  packages/opencensus-core/src/trace/model/tracer.ts
  packages/opencensus-core/src/trace/model/types.ts
  packages/opencensus-core/src/trace/types.ts
  packages/opencensus-core/test/test-console-exporter.ts
  packages/opencensus-core/test/test-exporter-buffer.ts
  packages/opencensus-core/test/test-root-span.ts
  packages/opencensus-core/test/test-tracer-base.ts
  packages/opencensus-core/test/test-tracer.ts
  packages/opencensus-exporter-jaeger/test/test-jaeger.ts
  packages/opencensus-exporter-ocagent/package-lock.json
  packages/opencensus-exporter-ocagent/test/test-ocagent.ts
  packages/opencensus-exporter-stackdriver/test/test-stackdriver-cloudtrace.ts
  packages/opencensus-instrumentation-http/src/http.ts
  packages/opencensus-instrumentation-ioredis/src/ioredis.ts
  packages/opencensus-instrumentation-mongodb/src/mongodb.ts
  packages/opencensus-instrumentation-redis/src/redis.ts
  packages/opencensus-nodejs/README.md
Labels: cla: yes

#497 chore(package): update handlebar to avoid security vulnerability
  package-lock.json
Labels: cla: yes

#494 fix(exporter-zpages): zpages template scope
  packages/opencensus-exporter-zpages/src/zpages-frontend/page-handlers/tracez.page-handler.ts
Labels: cla: yes

#496 feat(core): support object type attribute on spans
  packages/opencensus-core/src/trace/model/no-record/no-record-span.ts
  packages/opencensus-core/src/trace/model/span.ts
  packages/opencensus-core/src/trace/model/types.ts
  packages/opencensus-core/test/test-span.ts
Labels: cla: yes

#502 Remove "triage me" label from ISSUE_TEMPLATE
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: cla: yes

#493 fix(tracer): report every span to exporters
  packages/opencensus-core/src/exporters/console-exporter.ts
  packages/opencensus-core/src/exporters/exporter-buffer.ts
  packages/opencensus-core/src/trace/model/root-span.ts
  packages/opencensus-core/src/trace/model/span.ts
  packages/opencensus-core/src/trace/model/tracer-base.ts
  packages/opencensus-core/test/test-root-span.ts
  packages/opencensus-core/test/test-span.ts
  packages/opencensus-exporter-instana/src/instana.ts
  packages/opencensus-exporter-jaeger/src/jaeger.ts
  packages/opencensus-exporter-ocagent/src/ocagent.ts
  packages/opencensus-exporter-stackdriver/src/stackdriver-cloudtrace.ts
  packages/opencensus-exporter-stackdriver/test/test-stackdriver-cloudtrace.ts
  packages/opencensus-exporter-zipkin/src/zipkin.ts
  packages/opencensus-exporter-zipkin/test/test-zipkin.ts
  packages/opencensus-exporter-zpages/src/zpages.ts
  packages/opencensus-instrumentation-grpc/test/test-grpc.ts
  packages/opencensus-instrumentation-http/test/test-http.ts
  packages/opencensus-instrumentation-http2/test/test-http2.ts
  packages/opencensus-instrumentation-https/test/test-https.ts
  packages/opencensus-instrumentation-ioredis/test/test-ioredis.ts
  packages/opencensus-instrumentation-mongodb/test/test-mongodb.ts
  packages/opencensus-instrumentation-redis/test/test-redis.ts
Labels: cla: yes

#508 chore(lerna): add fix script
  package.json
Labels: cla: yes

#509 Fix README badge URLs
  README.md
Labels: cla: yes

#505 Plug-in Cumulative APIs into the Metric-Registry
  CHANGELOG.md
  packages/opencensus-core/src/metrics/metric-registry.ts
  packages/opencensus-core/test/test-metric-registry.ts
Labels: cla: yes

#510 Cleanup: remove redundant types in JSDoc
  examples/stats/exporter/prometheus.js
  examples/stats/exporter/stackdriver.js
  examples/stats/web_client_monitoring/web_client/metricsclient.js
  packages/opencensus-core/src/common/time-util.ts
  packages/opencensus-core/src/common/validations.ts
  packages/opencensus-core/src/internal/string-utils.ts
  packages/opencensus-core/src/metrics/cumulative/cumulative.ts
  packages/opencensus-core/src/metrics/cumulative/types.ts
  packages/opencensus-core/src/metrics/export/base-metric-producer.ts
  packages/opencensus-core/src/metrics/export/metric-producer-manager.ts
  packages/opencensus-core/src/metrics/gauges/derived-gauge.ts
  packages/opencensus-core/src/metrics/gauges/gauge.ts
  packages/opencensus-core/src/metrics/gauges/types.ts
  packages/opencensus-core/src/metrics/types.ts
  packages/opencensus-core/src/metrics/utils.ts
  packages/opencensus-core/src/resource/resource.ts
  packages/opencensus-core/src/stats/metric-producer.ts
  packages/opencensus-core/src/stats/metric-utils.ts
  packages/opencensus-core/src/stats/stats.ts
  packages/opencensus-core/src/stats/types.ts
  packages/opencensus-core/src/stats/view.ts
Labels: cla: yes, document

#514 feat(core): start tracer with span attributes
  CHANGELOG.md
  packages/opencensus-core/src/trace/config/types.ts
  packages/opencensus-core/src/trace/model/tracer-base.ts
  packages/opencensus-core/test/test-tracer-base.ts
  packages/opencensus-nodejs/README.md
Labels: cla: yes

#516 Fix vulnerable dependencies: mocha
  packages/opencensus-core/package-lock.json
  packages/opencensus-core/package.json
  packages/opencensus-exporter-instana/package-lock.json
  packages/opencensus-exporter-instana/package.json
  packages/opencensus-exporter-jaeger/package-lock.json
  packages/opencensus-exporter-jaeger/package.json
  packages/opencensus-exporter-ocagent/package-lock.json
  packages/opencensus-exporter-ocagent/package.json
  packages/opencensus-exporter-prometheus/package-lock.json
  packages/opencensus-exporter-prometheus/package.json
  packages/opencensus-exporter-stackdriver/package-lock.json
  packages/opencensus-exporter-stackdriver/package.json
  packages/opencensus-exporter-zipkin/package-lock.json
  packages/opencensus-exporter-zipkin/package.json
  packages/opencensus-exporter-zpages/package-lock.json
  packages/opencensus-exporter-zpages/package.json
  packages/opencensus-instrumentation-grpc/package-lock.json
  packages/opencensus-instrumentation-grpc/package.json
  packages/opencensus-instrumentation-http/package-lock.json
  packages/opencensus-instrumentation-http/package.json
  packages/opencensus-instrumentation-http2/package-lock.json
  packages/opencensus-instrumentation-http2/package.json
  packages/opencensus-instrumentation-https/package-lock.json
  packages/opencensus-instrumentation-https/package.json
  packages/opencensus-instrumentation-ioredis/package-lock.json
  packages/opencensus-instrumentation-ioredis/package.json
  packages/opencensus-instrumentation-mongodb/package-lock.json
  packages/opencensus-instrumentation-mongodb/package.json
  packages/opencensus-instrumentation-redis/package-lock.json
  packages/opencensus-instrumentation-redis/package.json
  packages/opencensus-nodejs-base/package-lock.json
  packages/opencensus-nodejs-base/package.json
  packages/opencensus-nodejs/package-lock.json
  packages/opencensus-nodejs/package.json
  packages/opencensus-propagation-b3/package-lock.json
  packages/opencensus-propagation-b3/package.json
  packages/opencensus-propagation-binaryformat/package-lock.json
  packages/opencensus-propagation-binaryformat/package.json
  packages/opencensus-propagation-jaeger/package-lock.json
  packages/opencensus-propagation-jaeger/package.json
  packages/opencensus-propagation-stackdriver/package-lock.json
  packages/opencensus-propagation-stackdriver/package.json
  packages/opencensus-propagation-tracecontext/package-lock.json
  packages/opencensus-propagation-tracecontext/package.json
  packages/opencensus-resource-util/package-lock.json
  packages/opencensus-resource-util/package.json
Labels: cla: yes, code health

#515 Instrumentation/HTTP: Handle incoming requests with long request url …
  packages/opencensus-instrumentation-http/src/http.ts
  packages/opencensus-instrumentation-http/test/test-http.ts
Labels: cla: yes

#513 Plug-in Derived Cumulative into the Metric-Registry
  CHANGELOG.md
  packages/opencensus-core/src/common/validations.ts
  packages/opencensus-core/src/metrics/metric-registry.ts
  packages/opencensus-core/test/test-metric-registry.ts
Labels: API, cla: yes

#517 chore(multiple): 0.0.12 release proposal
  lerna.json
  packages/opencensus-core/package.json
  packages/opencensus-example-automatic-tracing/package.json
  packages/opencensus-exporter-instana/package.json
  packages/opencensus-exporter-jaeger/package.json
  packages/opencensus-exporter-ocagent/package.json
  packages/opencensus-exporter-prometheus/package.json
  packages/opencensus-exporter-stackdriver/package.json
  packages/opencensus-exporter-zipkin/package.json
  packages/opencensus-exporter-zpages/package.json
  packages/opencensus-instrumentation-all/package.json
  packages/opencensus-instrumentation-grpc/package.json
  packages/opencensus-instrumentation-http/package.json
  packages/opencensus-instrumentation-http2/package.json
  packages/opencensus-instrumentation-https/package.json
  packages/opencensus-instrumentation-ioredis/package.json
  packages/opencensus-instrumentation-mongodb/package.json
  packages/opencensus-instrumentation-redis/package.json
  packages/opencensus-nodejs-base/package.json
  packages/opencensus-nodejs/package.json
  packages/opencensus-propagation-b3/package.json
  packages/opencensus-propagation-binaryformat/package.json
  packages/opencensus-propagation-jaeger/package.json
  packages/opencensus-propagation-stackdriver/package.json
  packages/opencensus-propagation-tracecontext/package.json
  packages/opencensus-resource-util/package.json
Labels: cla: yes

#518 Post Release: update CHANGELOG and Examples
  CHANGELOG.md
  examples/grpc/package.json
  examples/http/package.json
  examples/stats/exporter/package.json
  examples/stats/web_client_monitoring/package.json
  packages/opencensus-exporter-prometheus/src/prometheus-stats.ts
Labels: cla: yes

#519 Fix missing gitter links
  packages/opencensus-nodejs-base/README.md
Labels: cla: yes

#524 Chore: remove node 6 ci job
  .circleci/config.yml
Labels: cla: yes

#525 Cleanup type assertion
  packages/opencensus-core/src/metrics/gauges/derived-gauge.ts
  packages/opencensus-core/src/stats/view.ts
  packages/opencensus-core/src/trace/model/span.ts
  packages/opencensus-core/test/test-root-span.ts
  packages/opencensus-core/test/test-span.ts
  packages/opencensus-core/test/test-tracer-base.ts
  packages/opencensus-exporter-jaeger/test/test-jaeger.ts
  packages/opencensus-exporter-stackdriver/test/test-stackdriver-cloudtrace.ts
  packages/opencensus-exporter-stackdriver/test/test-stackdriver-monitoring-utils.ts
  packages/opencensus-exporter-zipkin/src/zipkin.ts
  packages/opencensus-exporter-zipkin/test/test-zipkin.ts
  packages/opencensus-exporter-zpages/README.md
  packages/opencensus-exporter-zpages/src/zpages.ts
  packages/opencensus-exporter-zpages/test/test-zpages.ts
  packages/opencensus-instrumentation-http/test/test-http.ts
Labels: cla: yes

#521 `startChildSpan` with `SpanOptions` interface only.
  CHANGELOG.md
  packages/opencensus-core/src/trace/model/no-record/no-record-span.ts
  packages/opencensus-core/src/trace/model/span.ts
  packages/opencensus-core/src/trace/model/tracer-base.ts
  packages/opencensus-core/src/trace/model/types.ts
Labels: cla: yes

#528 Change CLS import to make stats types more general. (Fix #527)
  packages/opencensus-core/src/stats/types.ts
  packages/opencensus-core/src/trace/instrumentation/types.ts
Labels: cla: yes

#523 Fix vulnerable dependencies: Codecov
  packages/opencensus-core/package-lock.json
  packages/opencensus-core/package.json
  packages/opencensus-exporter-instana/package-lock.json
  packages/opencensus-exporter-instana/package.json
  packages/opencensus-exporter-jaeger/package-lock.json
  packages/opencensus-exporter-jaeger/package.json
  packages/opencensus-exporter-ocagent/package-lock.json
  packages/opencensus-exporter-ocagent/package.json
  packages/opencensus-exporter-prometheus/package-lock.json
  packages/opencensus-exporter-prometheus/package.json
  packages/opencensus-exporter-stackdriver/package-lock.json
  packages/opencensus-exporter-stackdriver/package.json
  packages/opencensus-exporter-zipkin/package-lock.json
  packages/opencensus-exporter-zipkin/package.json
  packages/opencensus-exporter-zpages/package-lock.json
  packages/opencensus-exporter-zpages/package.json
  packages/opencensus-instrumentation-grpc/package-lock.json
  packages/opencensus-instrumentation-grpc/package.json
  packages/opencensus-instrumentation-http/package-lock.json
  packages/opencensus-instrumentation-http/package.json
  packages/opencensus-instrumentation-http2/package-lock.json
  packages/opencensus-instrumentation-http2/package.json
  packages/opencensus-instrumentation-https/package-lock.json
  packages/opencensus-instrumentation-https/package.json
  packages/opencensus-instrumentation-ioredis/package-lock.json
  packages/opencensus-instrumentation-ioredis/package.json
  packages/opencensus-instrumentation-mongodb/package-lock.json
  packages/opencensus-instrumentation-mongodb/package.json
  packages/opencensus-instrumentation-redis/package-lock.json
  packages/opencensus-instrumentation-redis/package.json
  packages/opencensus-nodejs-base/package-lock.json
  packages/opencensus-nodejs-base/package.json
  packages/opencensus-nodejs/package-lock.json
  packages/opencensus-nodejs/package.json
  packages/opencensus-propagation-b3/package-lock.json
  packages/opencensus-propagation-b3/package.json
  packages/opencensus-propagation-binaryformat/package-lock.json
  packages/opencensus-propagation-binaryformat/package.json
  packages/opencensus-propagation-jaeger/package-lock.json
  packages/opencensus-propagation-jaeger/package.json
  packages/opencensus-propagation-stackdriver/package-lock.json
  packages/opencensus-propagation-stackdriver/package.json
  packages/opencensus-propagation-tracecontext/package-lock.json
  packages/opencensus-propagation-tracecontext/package.json
  packages/opencensus-resource-util/package-lock.json
  packages/opencensus-resource-util/package.json
Labels: cla: yes

#531 doc: add some use info to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: cla: yes

#530 Fix: handle infinite loop caused by get traceState()
  packages/opencensus-core/src/trace/model/no-record/no-record-span.ts
  packages/opencensus-core/test/test-no-record-root-span.ts
  packages/opencensus-core/test/test-no-record-span.ts
  packages/opencensus-core/test/test-root-span.ts
  packages/opencensus-core/test/test-span.ts
Labels: cla: yes

#522 Fix jaeger config syntax
  packages/opencensus-exporter-jaeger/README.md
Labels: cla: yes

#533 Chore: upgrade engines field to >=8
  examples/grpc/package.json
  examples/http/package.json
  examples/stats/exporter/package.json
  package.json
  packages/opencensus-core/package.json
  packages/opencensus-exporter-instana/package.json
  packages/opencensus-exporter-jaeger/package.json
  packages/opencensus-exporter-ocagent/package.json
  packages/opencensus-exporter-prometheus/package.json
  packages/opencensus-exporter-stackdriver/package.json
  packages/opencensus-exporter-zipkin/package.json
  packages/opencensus-exporter-zpages/package.json
  packages/opencensus-instrumentation-all/package.json
  packages/opencensus-instrumentation-grpc/package.json
  packages/opencensus-instrumentation-http/package.json
  packages/opencensus-instrumentation-http2/package.json
  packages/opencensus-instrumentation-https/package.json
  packages/opencensus-instrumentation-ioredis/package.json
  packages/opencensus-instrumentation-mongodb/package.json
  packages/opencensus-instrumentation-redis/package.json
  packages/opencensus-nodejs-base/package.json
  packages/opencensus-nodejs/package.json
  packages/opencensus-propagation-b3/package.json
  packages/opencensus-propagation-binaryformat/package.json
  packages/opencensus-propagation-jaeger/package.json
  packages/opencensus-propagation-tracecontext/package.json
  packages/opencensus-resource-util/package.json
Labels: cla: yes

#535 Chore: update GRPC to 1.12.3
  packages/opencensus-exporter-ocagent/package-lock.json
  packages/opencensus-exporter-ocagent/package.json
Labels: cla: yes

#532 set CurrentRootSpan correctly
  packages/opencensus-core/src/trace/model/span.ts
  packages/opencensus-core/src/trace/model/tracer-base.ts
  packages/opencensus-core/src/trace/model/tracer.ts
  packages/opencensus-core/src/trace/model/types.ts
Labels: cla: yes

#492 Add support for custom attributes
  CHANGELOG.md
  packages/opencensus-core/src/trace/instrumentation/types.ts
  packages/opencensus-instrumentation-http/src/http.ts
  packages/opencensus-instrumentation-http/src/types.ts
  packages/opencensus-instrumentation-http/test/test-http.ts
  packages/opencensus-instrumentation-https/test/test-https.ts
Labels: cla: yes

#538 Exporter/Prometheus: Fix missing tags for HTTP metrics
  packages/opencensus-exporter-prometheus/src/prometheus-stats.ts
  packages/opencensus-exporter-prometheus/test/test-prometheus-stats.ts
Labels: cla: yes

#539 chore(multiple): 0.0.13 release proposal
  lerna.json
  packages/opencensus-core/package.json
  packages/opencensus-example-automatic-tracing/package.json
  packages/opencensus-exporter-instana/package.json
  packages/opencensus-exporter-jaeger/package.json
  packages/opencensus-exporter-ocagent/package.json
  packages/opencensus-exporter-prometheus/package.json
  packages/opencensus-exporter-prometheus/src/prometheus-stats.ts
  packages/opencensus-exporter-stackdriver/package.json
  packages/opencensus-exporter-zipkin/package.json
  packages/opencensus-exporter-zpages/package.json
  packages/opencensus-instrumentation-all/package.json
  packages/opencensus-instrumentation-grpc/package.json
  packages/opencensus-instrumentation-http/package.json
  packages/opencensus-instrumentation-http2/package.json
  packages/opencensus-instrumentation-https/package.json
  packages/opencensus-instrumentation-ioredis/package.json
  packages/opencensus-instrumentation-mongodb/package.json
  packages/opencensus-instrumentation-redis/package.json
  packages/opencensus-nodejs-base/package.json
  packages/opencensus-nodejs/package.json
  packages/opencensus-propagation-b3/package.json
  packages/opencensus-propagation-binaryformat/package.json
  packages/opencensus-propagation-jaeger/package.json
  packages/opencensus-propagation-stackdriver/package.json
  packages/opencensus-propagation-tracecontext/package.json
  packages/opencensus-resource-util/package.json
Labels: cla: yes

#540 Post Release: update CHANGELOG and Examples
  CHANGELOG.md
  examples/grpc/package.json
  examples/http/package.json
  examples/stats/exporter/package.json
  examples/stats/web_client_monitoring/package.json
Labels: cla: yes

#504 chore: add node 12 ci job
  .circleci/config.yml
Labels: Draft, cla: yes

#520 Exporter/Stackdriver: Support Exemplar in Stackdriver TimeSeries
  CHANGELOG.md
  packages/opencensus-exporter-stackdriver/src/stackdriver-monitoring-utils.ts
  packages/opencensus-exporter-stackdriver/src/types.ts
  packages/opencensus-exporter-stackdriver/test/test-stackdriver-monitoring-utils.ts
Labels: cla: yes

#541 Enable to receive credentials object in creating Stackdriver exporter
  CHANGELOG.md
  packages/opencensus-exporter-stackdriver/src/stackdriver-cloudtrace.ts
  packages/opencensus-exporter-stackdriver/src/stackdriver-monitoring.ts
  packages/opencensus-exporter-stackdriver/src/types.ts
  packages/opencensus-exporter-stackdriver/test/test-stackdriver-cloudtrace.ts
Labels: cla: yes

#545 Fix duplicate spans issue and clean up
  packages/opencensus-core/src/exporters/console-exporter.ts
  packages/opencensus-core/src/exporters/types.ts
  packages/opencensus-core/src/trace/model/no-record/no-record-root-span.ts
  packages/opencensus-core/src/trace/model/no-record/no-record-span.ts
  packages/opencensus-core/src/trace/model/root-span.ts
  packages/opencensus-core/src/trace/model/span.ts
  packages/opencensus-core/src/trace/model/tracer-base.ts
  packages/opencensus-core/src/trace/model/tracer.ts
  packages/opencensus-core/src/trace/model/types.ts
  packages/opencensus-exporter-instana/src/instana.ts
  packages/opencensus-exporter-jaeger/src/jaeger.ts
  packages/opencensus-exporter-ocagent/src/adapters.ts
  packages/opencensus-exporter-ocagent/src/ocagent.ts
  packages/opencensus-exporter-stackdriver/src/stackdriver-cloudtrace.ts
  packages/opencensus-exporter-stackdriver/test/test-stackdriver-cloudtrace.ts
  packages/opencensus-exporter-zipkin/src/zipkin.ts
Labels: cla: yes

#547 Trace Context Propagation: return null instead of empty spancontext
  packages/opencensus-propagation-tracecontext/src/tracecontext-format.ts
  packages/opencensus-propagation-tracecontext/test/test-tracecontext-format.ts
Labels: cla: yes

#561 Fix: typo in prometheus version
  packages/opencensus-exporter-prometheus/src/prometheus-stats.ts
Labels: cla: yes

#485 Refactor resource util to match specs.
  packages/opencensus-exporter-stackdriver/src/common-utils.ts
  packages/opencensus-exporter-stackdriver/test/test-stackdriver-monitoring-utils.ts
  packages/opencensus-resource-util/src/constants.ts
  packages/opencensus-resource-util/src/index.ts
  packages/opencensus-resource-util/src/resource-labels.ts
  packages/opencensus-resource-util/src/resource-utils.ts
  packages/opencensus-resource-util/test/test-detect-resource.ts
Labels: Resource, cla: yes, enhancement

#562 Replace assert.equal with assert.strictEqual
  packages/opencensus-core/test/test-binary-serializer.ts
  packages/opencensus-core/test/test-console-logger.ts
  packages/opencensus-core/test/test-cumulative.ts
  packages/opencensus-core/test/test-derived-cumulative.ts
  packages/opencensus-core/test/test-derived-gauge.ts
  packages/opencensus-core/test/test-gauge.ts
  packages/opencensus-core/test/test-metric-component.ts
  packages/opencensus-core/test/test-metric-producer-manager.ts
  packages/opencensus-core/test/test-metric-producer.ts
  packages/opencensus-core/test/test-metric-registry.ts
  packages/opencensus-core/test/test-no-record-root-span.ts
  packages/opencensus-core/test/test-no-record-span.ts
  packages/opencensus-core/test/test-recorder.ts
  packages/opencensus-core/test/test-resource.ts
  packages/opencensus-core/test/test-root-span.ts
  packages/opencensus-core/test/test-sampler.ts
  packages/opencensus-core/test/test-span.ts
  packages/opencensus-core/test/test-stats.ts
  packages/opencensus-core/test/test-tag-map.ts
  packages/opencensus-core/test/test-text-format.ts
  packages/opencensus-core/test/test-tracer-base.ts
  packages/opencensus-core/test/test-validation.ts
  packages/opencensus-core/test/test-variant-encoding.ts
  packages/opencensus-core/test/test-view.ts
  packages/opencensus-exporter-jaeger/test/test-jaeger.ts
  packages/opencensus-exporter-ocagent/test/test-ocagent.ts
  packages/opencensus-exporter-prometheus/test/test-prometheus-stats.ts
  packages/opencensus-exporter-stackdriver/test/test-stackdriver-cloudtrace-utils.ts
  packages/opencensus-exporter-stackdriver/test/test-stackdriver-cloudtrace.ts
  packages/opencensus-exporter-stackdriver/test/test-stackdriver-monitoring-utils.ts
  packages/opencensus-exporter-stackdriver/test/test-stackdriver-monitoring.ts
  packages/opencensus-exporter-zipkin/test/test-zipkin.ts
  packages/opencensus-exporter-zpages/test/test-zpages.ts
  packages/opencensus-instrumentation-http/test/test-http.ts
  packages/opencensus-instrumentation-http2/test/test-http2.ts
  packages/opencensus-instrumentation-https/test/test-https.ts
  packages/opencensus-resource-util/test/test-detect-resource.ts
Labels: cla: yes

#563 Replace assert.deepEqual with assert.deepStrictEqual
  packages/opencensus-core/test/test-binary-serializer.ts
  packages/opencensus-core/test/test-derived-cumulative.ts
  packages/opencensus-core/test/test-derived-gauge.ts
  packages/opencensus-core/test/test-gauge.ts
  packages/opencensus-core/test/test-metric-producer-manager.ts
  packages/opencensus-core/test/test-resource.ts
  packages/opencensus-core/test/test-root-span.ts
  packages/opencensus-core/test/test-span.ts
  packages/opencensus-core/test/test-stats.ts
  packages/opencensus-core/test/test-text-format.ts
  packages/opencensus-core/test/test-variant-encoding.ts
  packages/opencensus-core/test/test-view.ts
  packages/opencensus-exporter-jaeger/test/test-jaeger.ts
  packages/opencensus-exporter-ocagent/test/test-ocagent.ts
  packages/opencensus-exporter-stackdriver/test/test-stackdriver-cloudtrace-utils.ts
  packages/opencensus-exporter-stackdriver/test/test-stackdriver-cloudtrace.ts
  packages/opencensus-exporter-stackdriver/test/test-stackdriver-monitoring-utils.ts
  packages/opencensus-exporter-zipkin/test/test-zipkin.ts
  packages/opencensus-exporter-zpages/test/test-zpages.ts
  packages/opencensus-instrumentation-grpc/test/test-grpc.ts
  packages/opencensus-nodejs-base/test/test-tracing.ts
  packages/opencensus-propagation-b3/test/test-b3-format.ts
  packages/opencensus-propagation-jaeger/test/test-jaeger-format.ts
  packages/opencensus-propagation-stackdriver/test/test-stackdriver-format.ts
  packages/opencensus-propagation-stackdriver/test/test-v1.ts
  packages/opencensus-propagation-tracecontext/test/test-tracecontext-format.ts
  packages/opencensus-resource-util/test/test-detect-resource.ts
Labels: cla: yes
