Repository census-instrumentation/opencensus-node, pull requests merged in 2019-01, with the labels that each got.

#259 Add start method to StatsEventListener
  packages/opencensus-core/src/exporters/console-exporter.ts
  packages/opencensus-core/src/exporters/types.ts
  packages/opencensus-core/src/stats/stats.ts
  packages/opencensus-core/test/test-stats.ts
  packages/opencensus-exporter-prometheus/src/prometheus-stats.ts
  packages/opencensus-exporter-stackdriver/src/stackdriver-monitoring.ts
  packages/opencensus-exporter-zpages/src/zpages.ts
Labels: API, Metrics, cla: yes, exporters

#253 Add MetricProducerManager to keep track of all MetricProducers
  packages/opencensus-core/src/metrics/export/base-metric-producer.ts
  packages/opencensus-core/src/metrics/export/metric-producer-manager.ts
  packages/opencensus-core/src/metrics/export/types.ts
  packages/opencensus-core/src/metrics/metric-component.ts
  packages/opencensus-core/src/metrics/metric-registry.ts
  packages/opencensus-core/src/metrics/metrics.ts
  packages/opencensus-core/src/stats/metric-producer.ts
  packages/opencensus-core/src/stats/stats.ts
  packages/opencensus-core/test/test-metric-component.ts
  packages/opencensus-core/test/test-metric-producer-manager.ts
Labels: cla: yes

#254 Remove mocha type reference in `@opencensus/core` release code
  packages/opencensus-core/package.json
  packages/opencensus-core/tsconfig-release.json
Labels: cla: yes

#265 export Metrics classes and types
  packages/opencensus-core/src/index.ts
  packages/opencensus-core/test/test-metric-component.ts
Labels: cla: yes

#266 Add helper util to convert OC Metrics data models to SD monitoring data models
  package-lock.json
  packages/opencensus-core/package-lock.json
  packages/opencensus-exporter-stackdriver/src/stackdriver-stats-utils.ts
  packages/opencensus-exporter-stackdriver/src/types.ts
  packages/opencensus-exporter-stackdriver/test/test-stackdriver-stats-utils.ts
Labels: Metrics, cla: yes, exporters

#271 Simplify Logger interface, remove silly, make level optional
  CHANGELOG.md
  packages/opencensus-core/src/common/console-logger.ts
  packages/opencensus-core/src/common/types.ts
  packages/opencensus-core/test/test-console-logger.ts
  packages/opencensus-exporter-stackdriver/test/test-stackdriver-monitoring.ts
Labels: cla: yes

#273 Set startTimestamp to creation time of cumulative view
  packages/opencensus-core/src/common/time-util.ts
  packages/opencensus-core/src/stats/stats.ts
  packages/opencensus-core/src/stats/types.ts
  packages/opencensus-core/src/stats/view.ts
  packages/opencensus-core/test/test-view.ts
Labels: cla: yes

#277 Nit: Export for tests and Singleton instance for BaseMetricProducerMa…
  packages/opencensus-core/src/metrics/export/metric-producer-manager.ts
  packages/opencensus-exporter-stackdriver/src/stackdriver-stats-utils.ts
  packages/opencensus-exporter-stackdriver/test/test-stackdriver-stats-utils.ts
Labels: cla: yes

#275 Stats/Stackdriver: export data using metrics API
  packages/opencensus-core/src/stats/stats.ts
  packages/opencensus-exporter-stackdriver/src/stackdriver-monitoring.ts
  packages/opencensus-exporter-stackdriver/test/test-stackdriver-monitoring.ts
Labels: Metrics, cla: yes, exporters

#280 Add validation for tagkey & tagvalue. Fix issue #268
  packages/opencensus-core/src/stats/view.ts
  packages/opencensus-core/test/test-view.ts
Labels: API, cla: yes, tags

#295 [core] Add Tags API
  .gitignore
  packages/opencensus-core/src/index.ts
  packages/opencensus-core/src/tags/tag-map.ts
  packages/opencensus-core/src/tags/types.ts
  packages/opencensus-core/src/tags/validation.ts
  packages/opencensus-core/test/test-tag-map.ts
  packages/opencensus-core/test/test-validation.ts
Labels: cla: yes

#299 Add `opencensus-resource-util` package
  CHANGELOG.md
  packages/opencensus-core/src/index.ts
  packages/opencensus-core/src/resource/resource.ts
  packages/opencensus-core/test/test-resource.ts
  packages/opencensus-resource-util/AUTHORS
  packages/opencensus-resource-util/LICENSE
  packages/opencensus-resource-util/README.md
  packages/opencensus-resource-util/codecov.yml
  packages/opencensus-resource-util/package-lock.json
  packages/opencensus-resource-util/package.json
  packages/opencensus-resource-util/src/index.ts
  packages/opencensus-resource-util/src/resource-labels.ts
  packages/opencensus-resource-util/src/types.ts
  packages/opencensus-resource-util/tsconfig.json
Labels: cla: yes

#300 Add usage instructions
  packages/opencensus-exporter-jaeger/README.md
Labels: cla: yes

#291 Make Stats singleton (globalStats), separate registerView from createView
  CHANGELOG.md
  packages/opencensus-core/src/index.ts
  packages/opencensus-core/src/stats/metric-producer.ts
  packages/opencensus-core/src/stats/stats.ts
  packages/opencensus-core/src/stats/types.ts
  packages/opencensus-core/test/test-metric-producer.ts
  packages/opencensus-core/test/test-stats.ts
  packages/opencensus-exporter-prometheus/test/test-prometheus-stats.ts
  packages/opencensus-exporter-stackdriver/test/test-stackdriver-monitoring.ts
  packages/opencensus-exporter-zpages/test/test-zpages.ts
Labels: cla: yes

#309 Pin mongodb dependency
  packages/opencensus-instrumentation-mongodb/package-lock.json
  packages/opencensus-instrumentation-mongodb/package.json
Labels: cla: yes

#307 Update stats, zpages, prometheus packages with new Tags API
  CHANGELOG.md
  packages/opencensus-core/src/exporters/console-exporter.ts
  packages/opencensus-core/src/exporters/types.ts
  packages/opencensus-core/src/stats/metric-utils.ts
  packages/opencensus-core/src/stats/recorder.ts
  packages/opencensus-core/src/stats/stats.ts
  packages/opencensus-core/src/stats/types.ts
  packages/opencensus-core/src/stats/view.ts
  packages/opencensus-core/src/tags/tag-map.ts
  packages/opencensus-core/src/tags/validation.ts
  packages/opencensus-core/test/test-metric-producer.ts
  packages/opencensus-core/test/test-metric-utils.ts
  packages/opencensus-core/test/test-recorder.ts
  packages/opencensus-core/test/test-stats.ts
  packages/opencensus-core/test/test-view.ts
  packages/opencensus-exporter-prometheus/src/prometheus-stats.ts
  packages/opencensus-exporter-prometheus/test/test-prometheus-stats.ts
  packages/opencensus-exporter-stackdriver/src/stackdriver-monitoring.ts
  packages/opencensus-exporter-stackdriver/src/stackdriver-stats-utils.ts
  packages/opencensus-exporter-stackdriver/test/test-stackdriver-stats-utils.ts
  packages/opencensus-exporter-zpages/src/zpages-frontend/page-handlers/rpcz.page-handler.ts
  packages/opencensus-exporter-zpages/src/zpages-frontend/page-handlers/statsz.page-handler.ts
  packages/opencensus-exporter-zpages/src/zpages.ts
  packages/opencensus-exporter-zpages/templates/statsz-view-count.ejs
  packages/opencensus-exporter-zpages/templates/statsz-view-distribution.ejs
  packages/opencensus-exporter-zpages/templates/statsz-view-lastvalue.ejs
  packages/opencensus-exporter-zpages/templates/statsz-view-sum.ejs
  packages/opencensus-exporter-zpages/test/test-zpages.ts
Labels: cla: yes

#312 Auto detect GCE, GKE and AWS EC2 resources
  packages/opencensus-resource-util/package-lock.json
  packages/opencensus-resource-util/package.json
  packages/opencensus-resource-util/src/detect-resource.ts
  packages/opencensus-resource-util/src/index.ts
  packages/opencensus-resource-util/src/resource-utils.ts
  packages/opencensus-resource-util/test/test-detect-resource.ts
Labels: cla: yes

#314 Stats/Stackdriver: Use resource util to generate MonitoredResource
  packages/opencensus-exporter-stackdriver/package.json
  packages/opencensus-exporter-stackdriver/src/stackdriver-monitoring.ts
  packages/opencensus-exporter-stackdriver/src/stackdriver-stats-utils.ts
  packages/opencensus-exporter-stackdriver/test/nocks.ts
  packages/opencensus-exporter-stackdriver/test/test-stackdriver-monitoring.ts
  packages/opencensus-exporter-stackdriver/test/test-stackdriver-stats-utils.ts
  packages/opencensus-resource-util/src/resource-utils.ts
  packages/opencensus-resource-util/test/test-detect-resource.ts
Labels: cla: yes

#317 Update dependency google-auth-library
  packages/opencensus-exporter-stackdriver/package-lock.json
  packages/opencensus-exporter-stackdriver/package.json
Labels: cla: yes

#319 update googleapis -> 37.1.0
  packages/opencensus-exporter-stackdriver/package-lock.json
  packages/opencensus-exporter-stackdriver/package.json
Labels: cla: yes

#320 Stats/Stackdriver: Add user agent as client header
  packages/opencensus-exporter-stackdriver/src/stackdriver-monitoring.ts
Labels: cla: yes

#311 Add trace params
  packages/opencensus-core/src/trace/config/types.ts
  packages/opencensus-core/src/trace/model/tracer.ts
  packages/opencensus-core/src/trace/sampler/sampler.ts
  packages/opencensus-core/test/test-sampler.ts
  packages/opencensus-core/test/test-tracer.ts
Labels: cla: yes

#321 Exporter/Stackdriver: Add common utils
  packages/opencensus-exporter-stackdriver/src/common-utils.ts
  packages/opencensus-exporter-stackdriver/src/stackdriver-cloudtrace.ts
  packages/opencensus-exporter-stackdriver/src/stackdriver-monitoring.ts
  packages/opencensus-exporter-stackdriver/src/stackdriver-stats-utils.ts
  packages/opencensus-exporter-stackdriver/test/test-stackdriver-stats-utils.ts
  packages/opencensus-resource-util/src/resource-labels.ts
Labels: cla: yes
