Repository census-instrumentation/opencensus-node, pull requests merged in 2019-02, with the labels that each got.

#323 Add message event size fields
  CHANGELOG.md
  packages/opencensus-core/src/trace/model/types.ts
Labels: cla: yes

#328 Tracing: Add code and message to Span -> Status
  CHANGELOG.md
  packages/opencensus-core/src/trace/model/span-base.ts
  packages/opencensus-core/src/trace/model/types.ts
  packages/opencensus-core/test/test-span.ts
  packages/opencensus-exporter-instana/src/instana.ts
  packages/opencensus-exporter-ocagent/src/adapters.ts
  packages/opencensus-exporter-ocagent/test/test-ocagent.ts
  packages/opencensus-exporter-zpages/src/zpages-frontend/page-handlers/tracez.page-handler.ts
  packages/opencensus-exporter-zpages/src/zpages.ts
  packages/opencensus-instrumentation-grpc/src/grpc.ts
  packages/opencensus-instrumentation-grpc/test/test-grpc.ts
  packages/opencensus-instrumentation-http/src/http.ts
  packages/opencensus-instrumentation-http/test/test-http.ts
  packages/opencensus-instrumentation-http2/src/http2.ts
  packages/opencensus-instrumentation-http2/test/test-http2.ts
  packages/opencensus-instrumentation-https/test/test-https.ts
Labels: cla: yes

#330 Enforce attribute limit
  packages/opencensus-core/src/trace/model/root-span.ts
  packages/opencensus-core/src/trace/model/span-base.ts
  packages/opencensus-core/src/trace/model/span.ts
  packages/opencensus-core/src/trace/model/tracer.ts
  packages/opencensus-core/src/trace/model/types.ts
  packages/opencensus-core/test/test-tracer.ts
  packages/opencensus-exporter-ocagent/src/adapters.ts
  packages/opencensus-exporter-ocagent/test/test-ocagent.ts
  packages/opencensus-nodejs/src/trace/config/default-config.ts
  packages/opencensus-nodejs/src/trace/constants.ts
  packages/opencensus-nodejs/test/test-tracing.ts
Labels: GA-Effort, cla: yes

#331 Enforce Links limit
  packages/opencensus-core/src/trace/model/span-base.ts
  packages/opencensus-core/src/trace/model/types.ts
  packages/opencensus-core/test/test-root-span.ts
  packages/opencensus-core/test/test-span.ts
  packages/opencensus-exporter-ocagent/src/adapters.ts
  packages/opencensus-exporter-ocagent/test/test-ocagent.ts
Labels: GA-Effort, cla: yes

#335 Enforce message event and annotation limits.
  packages/opencensus-core/src/trace/model/span-base.ts
  packages/opencensus-core/src/trace/model/types.ts
  packages/opencensus-core/test/test-root-span.ts
  packages/opencensus-core/test/test-span.ts
  packages/opencensus-exporter-ocagent/src/adapters.ts
  packages/opencensus-exporter-ocagent/test/test-ocagent.ts
Labels: GA-Effort, cla: yes

#334 Use enum for MessageEvent Type, Link Type and SpanKind
  CHANGELOG.md
  packages/opencensus-core/src/trace/model/root-span.ts
  packages/opencensus-core/src/trace/model/span-base.ts
  packages/opencensus-core/src/trace/model/tracer.ts
  packages/opencensus-core/src/trace/model/types.ts
  packages/opencensus-core/test/test-console-exporter.ts
  packages/opencensus-core/test/test-exporter-buffer.ts
  packages/opencensus-core/test/test-root-span.ts
  packages/opencensus-core/test/test-span.ts
  packages/opencensus-core/test/test-tracer.ts
  packages/opencensus-exporter-instana/src/instana.ts
  packages/opencensus-exporter-instana/test/test-instana.ts
  packages/opencensus-exporter-ocagent/src/adapters.ts
  packages/opencensus-exporter-ocagent/test/test-ocagent.ts
  packages/opencensus-exporter-zipkin/test/test-zipkin.ts
  packages/opencensus-instrumentation-grpc/src/grpc.ts
  packages/opencensus-instrumentation-grpc/test/test-grpc.ts
  packages/opencensus-instrumentation-http/src/http.ts
  packages/opencensus-instrumentation-http2/src/http2.ts
  packages/opencensus-instrumentation-mongodb/src/mongodb.ts
  packages/opencensus-instrumentation-mongodb/test/test-mongodb.ts
Labels: GA-Effort, cla: yes

#339 Update examples to work with global stats instance
  README.md
  examples/stats/exporter/prometheus.js
  examples/stats/exporter/stackdriver.js
  examples/stats/web_client_monitoring/app.js
  package.json
  packages/opencensus-core/README.md
  packages/opencensus-core/package.json
  packages/opencensus-exporter-prometheus/README.md
  packages/opencensus-exporter-stackdriver/README.md
  packages/opencensus-exporter-stackdriver/package.json
Labels: GA-Effort, cla: yes

#338 Exporter/Stackdriver: Use Trace SDKs (v2 API)
  CHANGELOG.md
  packages/opencensus-exporter-stackdriver/src/stackdriver-cloudtrace-utils.ts
  packages/opencensus-exporter-stackdriver/src/stackdriver-cloudtrace.ts
  packages/opencensus-exporter-stackdriver/src/types.ts
  packages/opencensus-exporter-stackdriver/test/nocks.ts
  packages/opencensus-exporter-stackdriver/test/test-stackdriver-cloudtrace-utils.ts
  packages/opencensus-exporter-stackdriver/test/test-stackdriver-cloudtrace.ts
Labels: cla: yes

#341 chore(multiple): 0.0.9 release proposal
  lerna.json
  packages/opencensus-core/package.json
  packages/opencensus-example-automatic-tracing/package.json
  packages/opencensus-exporter-instana/package.json
  packages/opencensus-exporter-jaeger/package.json
  packages/opencensus-exporter-ocagent/package.json
  packages/opencensus-exporter-prometheus/package.json
  packages/opencensus-exporter-stackdriver/package.json
  packages/opencensus-exporter-zipkin/package.json
  packages/opencensus-exporter-zpages/package.json
  packages/opencensus-instrumentation-all/package.json
  packages/opencensus-instrumentation-grpc/package.json
  packages/opencensus-instrumentation-http/package.json
  packages/opencensus-instrumentation-http2/package.json
  packages/opencensus-instrumentation-https/package.json
  packages/opencensus-instrumentation-mongodb/package.json
  packages/opencensus-nodejs/package.json
  packages/opencensus-propagation-b3/package.json
  packages/opencensus-propagation-jaeger/package.json
  packages/opencensus-propagation-stackdriver/package.json
  packages/opencensus-propagation-tracecontext/package.json
  packages/opencensus-resource-util/package.json
Labels: cla: yes

#342 Post Release: update CHANGELOG and example
  CHANGELOG.md
  examples/stats/web_client_monitoring/package.json
Labels: cla: yes

#344 Add message sizes to `addMessageEvent` function
  CHANGELOG.md
  packages/opencensus-core/src/trace/model/span-base.ts
  packages/opencensus-core/src/trace/model/types.ts
  packages/opencensus-core/test/test-span.ts
Labels: cla: yes

#343 Add instrumentation for grpc
  packages/opencensus-instrumentation-grpc/src/grpc-stats/client-metrics.ts
  packages/opencensus-instrumentation-grpc/src/grpc-stats/server-metrics.ts
  packages/opencensus-instrumentation-grpc/src/grpc-stats/stats-common.ts
Labels: GA-Effort, cla: yes

#345 exporter/Zipkin: Add missing fields (Annotation,Status,MessageEvent etc)
  CHANGELOG.md
  packages/opencensus-exporter-zipkin/README.md
  packages/opencensus-exporter-zipkin/src/zipkin.ts
  packages/opencensus-exporter-zipkin/test/test-zipkin.ts
Labels: cla: yes

#347 Update uncompressedSize and compressedSize for the exporters
  packages/opencensus-core/src/trace/model/types.ts
  packages/opencensus-exporter-ocagent/src/adapters.ts
  packages/opencensus-exporter-ocagent/test/test-ocagent.ts
  packages/opencensus-exporter-stackdriver/src/stackdriver-cloudtrace-utils.ts
  packages/opencensus-exporter-stackdriver/test/test-stackdriver-cloudtrace-utils.ts
Labels: cla: yes

#324 fixes http.get patches for header propagation #117
  packages/opencensus-instrumentation-http/src/http.ts
  packages/opencensus-instrumentation-http/test/test-http.ts
Labels: cla: yes

#351 add default value when `attributes` are not specified
  packages/opencensus-core/src/trace/model/span-base.ts
  packages/opencensus-core/test/test-root-span.ts
  packages/opencensus-exporter-ocagent/test/test-ocagent.ts
Labels: cla: yes

#353 Add support for Binary propagation format
  CHANGELOG.md
  packages/opencensus-propagation-binaryformat/.npmignore
  packages/opencensus-propagation-binaryformat/AUTHORS
  packages/opencensus-propagation-binaryformat/LICENSE
  packages/opencensus-propagation-binaryformat/README.md
  packages/opencensus-propagation-binaryformat/codecov.yml
  packages/opencensus-propagation-binaryformat/package-lock.json
  packages/opencensus-propagation-binaryformat/package.json
  packages/opencensus-propagation-binaryformat/src/binary-format.ts
  packages/opencensus-propagation-binaryformat/src/index.ts
  packages/opencensus-propagation-binaryformat/test/test-binary-format.ts
  packages/opencensus-propagation-binaryformat/tsconfig.json
Labels: GA-Effort, cla: yes, gRPC, traces

#354 Use binary format for grpc plugin
  packages/opencensus-instrumentation-grpc/package.json
  packages/opencensus-instrumentation-grpc/src/grpc.ts
  packages/opencensus-instrumentation-grpc/test/test-grpc.ts
  packages/opencensus-instrumentation-grpc/tsconfig.json
  packages/opencensus-propagation-binaryformat/src/index.ts
Labels: GA-Effort, cla: yes, gRPC

#349 Add option of passing in an object(SpanOptions) to the startChildSpan
  CHANGELOG.md
  packages/opencensus-core/src/trace/model/root-span.ts
  packages/opencensus-core/src/trace/model/tracer.ts
  packages/opencensus-core/src/trace/model/types.ts
  packages/opencensus-core/test/test-root-span.ts
  packages/opencensus-core/test/test-tracer.ts
  packages/opencensus-exporter-instana/test/test-instana.ts
  packages/opencensus-exporter-zipkin/test/test-zipkin.ts
  packages/opencensus-exporter-zpages/test/test-zpages.ts
  packages/opencensus-instrumentation-grpc/src/grpc.ts
  packages/opencensus-instrumentation-http/src/http.ts
  packages/opencensus-instrumentation-http2/src/http2.ts
  packages/opencensus-instrumentation-mongodb/src/mongodb.ts
Labels: API, GA-Effort, cla: yes, traces

#355 Add gRPC integration guide
  examples/grpc/README.md
  examples/grpc/capitalize_client.js
  examples/grpc/capitalize_server.js
  examples/grpc/package.json
  examples/grpc/protos/defs.proto
  examples/grpc/stackdriver_grpc_nodejs.png
Labels: cla: yes

#363 Fix stackdriver test
  packages/opencensus-exporter-stackdriver/test/test-stackdriver-cloudtrace.ts
Labels: cla: yes

#360 Add Measure, TagKey and View constants for recording HTTP stats
  packages/opencensus-instrumentation-http/src/http-metrics.ts
Labels: cla: yes

#364 enforce strictNullChecks on HTTP plugin
  packages/opencensus-instrumentation-http/src/http.ts
  packages/opencensus-instrumentation-http/test/test-http.ts
  packages/opencensus-instrumentation-http/tsconfig.json
Labels: cla: yes

#366 Fix the exporter-ocagent
  CHANGELOG.md
  packages/opencensus-exporter-ocagent/README.md
  packages/opencensus-exporter-ocagent/package-lock.json
  packages/opencensus-exporter-ocagent/package.json
  packages/opencensus-exporter-ocagent/src/ocagent.ts
  packages/opencensus-exporter-ocagent/test/test-ocagent.ts
Labels: cla: yes

#357 Add support for recording gRPC stats
  packages/opencensus-core/src/trace/instrumentation/base-plugin.ts
  packages/opencensus-instrumentation-grpc/package-lock.json
  packages/opencensus-instrumentation-grpc/package.json
  packages/opencensus-instrumentation-grpc/src/grpc-stats/client-metrics.ts
  packages/opencensus-instrumentation-grpc/src/grpc-stats/common-distributions.ts
  packages/opencensus-instrumentation-grpc/src/grpc-stats/server-metrics.ts
  packages/opencensus-instrumentation-grpc/src/grpc-stats/stats-common.ts
  packages/opencensus-instrumentation-grpc/src/grpc.ts
  packages/opencensus-instrumentation-grpc/src/index.ts
  packages/opencensus-instrumentation-grpc/test/test-grpc.ts
Labels: cla: yes

#332 Add support for child span count
  packages/opencensus-core/src/trace/model/root-span.ts
  packages/opencensus-core/src/trace/model/types.ts
  packages/opencensus-core/test/test-root-span.ts
Labels: cla: yes

#371 Update examples with latest OC version and format using semistandard
  examples/stats/exporter/package.json
  examples/stats/exporter/prometheus.js
  examples/stats/exporter/stackdriver.js
Labels: cla: yes

#374 gRPC plugin : Rename metrics to stats
  packages/opencensus-instrumentation-grpc/src/grpc-stats/client-stats.ts
  packages/opencensus-instrumentation-grpc/src/grpc-stats/server-stats.ts
  packages/opencensus-instrumentation-grpc/src/grpc-stats/stats-common.ts
  packages/opencensus-instrumentation-grpc/src/grpc.ts
  packages/opencensus-instrumentation-grpc/test/test-grpc.ts
Labels: cla: yes

#369 Add HTTP instrumentation guide
  examples/http/README.md
  examples/http/client.js
  examples/http/package.json
  examples/http/server.js
  examples/http/zipkin_http_nodejs.png
  packages/opencensus-instrumentation-http/src/http.ts
Labels: GA-Effort, cla: yes
