Repository census-instrumentation/opencensus-node, pull requests merged in 2019-04, with the labels that each got.

#457 Fix docs
  packages/opencensus-core/src/common/console-logger.ts
  packages/opencensus-core/src/common/time-util.ts
  packages/opencensus-core/src/common/types.ts
  packages/opencensus-core/src/exporters/console-exporter.ts
  packages/opencensus-core/src/exporters/exporter-buffer.ts
  packages/opencensus-core/src/exporters/types.ts
  packages/opencensus-core/src/index.ts
  packages/opencensus-core/src/internal/clock.ts
  packages/opencensus-core/src/internal/string-utils.ts
  packages/opencensus-core/src/internal/util.ts
  packages/opencensus-core/src/metrics/export/base-metric-producer.ts
  packages/opencensus-core/src/metrics/export/metric-producer-manager.ts
  packages/opencensus-core/src/metrics/export/types.ts
  packages/opencensus-core/src/metrics/metric-component.ts
  packages/opencensus-core/src/metrics/metric-registry.ts
  packages/opencensus-core/src/resource/resource.ts
  packages/opencensus-core/src/stats/metric-producer.ts
  packages/opencensus-core/src/stats/metric-utils.ts
  packages/opencensus-core/src/stats/stats.ts
  packages/opencensus-core/src/stats/types.ts
  packages/opencensus-core/src/stats/view.ts
  packages/opencensus-core/src/tags/tag-map.ts
  packages/opencensus-core/src/tags/validation.ts
  packages/opencensus-core/src/trace/instrumentation/base-plugin.ts
  packages/opencensus-core/src/trace/instrumentation/types.ts
  packages/opencensus-core/src/trace/model/root-span.ts
  packages/opencensus-core/src/trace/model/span.ts
  packages/opencensus-core/src/trace/model/types.ts
  packages/opencensus-core/src/trace/sampler/sampler.ts
  packages/opencensus-core/src/trace/sampler/types.ts
  packages/opencensus-exporter-instana/src/instana.ts
  packages/opencensus-exporter-jaeger/src/jaeger.ts
  packages/opencensus-exporter-ocagent/package-lock.json
  packages/opencensus-exporter-ocagent/src/ocagent.ts
  packages/opencensus-exporter-ocagent/src/types/google.ts
  packages/opencensus-exporter-ocagent/src/types/opencensus.ts
  packages/opencensus-exporter-ocagent/src/types/trace-service.ts
  packages/opencensus-exporter-ocagent/test/test-ocagent.ts
  packages/opencensus-exporter-ocagent/tsconfig.json
  packages/opencensus-exporter-prometheus/src/prometheus-stats.ts
  packages/opencensus-exporter-stackdriver/src/stackdriver-cloudtrace.ts
  packages/opencensus-exporter-zpages/src/zpages-frontend/controllers/rpcz.controller.ts
  packages/opencensus-exporter-zpages/src/zpages-frontend/controllers/statsz.controller.ts
  packages/opencensus-exporter-zpages/src/zpages-frontend/controllers/traceconfigz.controller.ts
  packages/opencensus-exporter-zpages/src/zpages-frontend/controllers/tracez.controller.ts
  packages/opencensus-exporter-zpages/src/zpages-frontend/page-handlers/statsz.page-handler.ts
  packages/opencensus-exporter-zpages/src/zpages-frontend/page-handlers/traceconfigz.page-handler.ts
  packages/opencensus-exporter-zpages/src/zpages-frontend/page-handlers/tracez.page-handler.ts
  packages/opencensus-exporter-zpages/src/zpages-frontend/routes.ts
  packages/opencensus-instrumentation-grpc/src/grpc-stats/client-stats.ts
  packages/opencensus-instrumentation-grpc/src/grpc.ts
  packages/opencensus-instrumentation-http/src/http-stats.ts
  packages/opencensus-instrumentation-http/src/http.ts
  packages/opencensus-instrumentation-http/src/types.ts
  packages/opencensus-instrumentation-mongodb/src/mongodb.ts
  packages/opencensus-resource-util/src/types.ts
Labels: cla: yes, document, enhancement

#458 Add MetricOptions to simplify all addXGauge
  packages/opencensus-core/src/metrics/gauges/types.ts
  packages/opencensus-core/src/metrics/metric-registry.ts
  packages/opencensus-core/test/test-metric-registry.ts
  packages/opencensus-exporter-stackdriver/test/test-stackdriver-monitoring.ts
Labels: API, cla: yes, enhancement

#386 pass stats instance to plugin loader
  examples/http/client.js
  examples/http/package.json
  examples/http/server.js
  packages/opencensus-core/src/trace/config/types.ts
  packages/opencensus-nodejs/src/trace/instrumentation/plugin-loader.ts
  packages/opencensus-nodejs/src/trace/tracing.ts
Labels: cla: yes, opencensus-core, plugin

#460 Add gauge example
  examples/gauge/derived-gauge-quickstart.js
  examples/gauge/gauge-quickstart.js
Labels: cla: yes

#446 Message events: use counters instead of hexdecimal value
  CHANGELOG.md
  packages/opencensus-core/src/trace/model/no-record/no-record-span-base.ts
  packages/opencensus-core/src/trace/model/span-base.ts
  packages/opencensus-core/src/trace/model/types.ts
  packages/opencensus-core/test/test-no-record-root-span.ts
  packages/opencensus-core/test/test-no-record-span.ts
  packages/opencensus-core/test/test-root-span.ts
  packages/opencensus-core/test/test-span.ts
  packages/opencensus-exporter-ocagent/src/adapters.ts
  packages/opencensus-exporter-ocagent/test/test-ocagent.ts
  packages/opencensus-exporter-stackdriver/src/stackdriver-cloudtrace-utils.ts
  packages/opencensus-exporter-stackdriver/test/test-stackdriver-cloudtrace-utils.ts
  packages/opencensus-exporter-zipkin/test/test-zipkin.ts
  packages/opencensus-instrumentation-grpc/src/grpc.ts
  packages/opencensus-instrumentation-http/package-lock.json
  packages/opencensus-instrumentation-http/package.json
  packages/opencensus-instrumentation-http/src/http.ts
  packages/opencensus-instrumentation-http/test/test-http.ts
  packages/opencensus-instrumentation-http2/package-lock.json
  packages/opencensus-instrumentation-http2/package.json
  packages/opencensus-instrumentation-http2/src/http2.ts
  packages/opencensus-instrumentation-http2/test/test-http2.ts
Labels: cla: yes

#464 chore(multiple): 0.0.10 release proposal
  lerna.json
  packages/opencensus-core/package.json
  packages/opencensus-example-automatic-tracing/package.json
  packages/opencensus-exporter-instana/package.json
  packages/opencensus-exporter-jaeger/package-lock.json
  packages/opencensus-exporter-jaeger/package.json
  packages/opencensus-exporter-ocagent/package-lock.json
  packages/opencensus-exporter-ocagent/package.json
  packages/opencensus-exporter-prometheus/package-lock.json
  packages/opencensus-exporter-prometheus/package.json
  packages/opencensus-exporter-stackdriver/package-lock.json
  packages/opencensus-exporter-stackdriver/package.json
  packages/opencensus-exporter-zipkin/package.json
  packages/opencensus-exporter-zpages/package.json
  packages/opencensus-instrumentation-all/package.json
  packages/opencensus-instrumentation-grpc/package-lock.json
  packages/opencensus-instrumentation-grpc/package.json
  packages/opencensus-instrumentation-http/package.json
  packages/opencensus-instrumentation-http2/package-lock.json
  packages/opencensus-instrumentation-http2/package.json
  packages/opencensus-instrumentation-https/package-lock.json
  packages/opencensus-instrumentation-https/package.json
  packages/opencensus-instrumentation-ioredis/package.json
  packages/opencensus-instrumentation-mongodb/package-lock.json
  packages/opencensus-instrumentation-mongodb/package.json
  packages/opencensus-instrumentation-redis/package.json
  packages/opencensus-nodejs/package.json
  packages/opencensus-propagation-b3/package-lock.json
  packages/opencensus-propagation-b3/package.json
  packages/opencensus-propagation-binaryformat/package.json
  packages/opencensus-propagation-jaeger/package-lock.json
  packages/opencensus-propagation-jaeger/package.json
  packages/opencensus-propagation-stackdriver/package.json
  packages/opencensus-propagation-tracecontext/package-lock.json
  packages/opencensus-propagation-tracecontext/package.json
  packages/opencensus-resource-util/package-lock.json
  packages/opencensus-resource-util/package.json
Labels: cla: yes

#465 Post Release: update CHANGELOG, examples and ReadMe
  CHANGELOG.md
  examples/grpc/package.json
  examples/http/package.json
  examples/stats/exporter/package.json
  examples/stats/web_client_monitoring/package.json
  packages/opencensus-exporter-instana/README.md
  packages/opencensus-exporter-jaeger/README.md
  packages/opencensus-exporter-ocagent/README.md
  packages/opencensus-exporter-prometheus/src/prometheus-stats.ts
  packages/opencensus-exporter-stackdriver/README.md
  packages/opencensus-exporter-zipkin/README.md
  packages/opencensus-exporter-zpages/README.md
  packages/opencensus-instrumentation-grpc/README.md
  packages/opencensus-instrumentation-http/README.md
  packages/opencensus-instrumentation-http2/README.md
  packages/opencensus-instrumentation-https/README.md
  packages/opencensus-instrumentation-ioredis/README.md
  packages/opencensus-instrumentation-mongodb/README.md
  packages/opencensus-instrumentation-redis/README.md
  packages/opencensus-propagation-b3/README.md
  packages/opencensus-propagation-binaryformat/README.md
  packages/opencensus-propagation-jaeger/README.md
  packages/opencensus-propagation-stackdriver/README.md
  packages/opencensus-propagation-tracecontext/README.md
  packages/opencensus-resource-util/README.md
Labels: cla: yes

#466 Update RELEASING.md
  RELEASING.md
Labels: cla: yes

#468 Gauge: Add support for constant labels
  CHANGELOG.md
  packages/opencensus-core/src/common/validations.ts
  packages/opencensus-core/src/metrics/gauges/derived-gauge.ts
  packages/opencensus-core/src/metrics/gauges/gauge.ts
  packages/opencensus-core/src/metrics/metric-registry.ts
  packages/opencensus-core/test/test-derived-gauge.ts
  packages/opencensus-core/test/test-gauge.ts
  packages/opencensus-core/test/test-metric-registry.ts
Labels: cla: yes

#467 Fix: createScopedRequired depcreated in google-auth-library 3.0.0
  packages/opencensus-exporter-stackdriver/src/stackdriver-cloudtrace.ts
  packages/opencensus-exporter-stackdriver/src/stackdriver-monitoring.ts
Labels: cla: yes

#475 Fix error in opencensus to stackdriver translation (#474)
  packages/opencensus-exporter-stackdriver/src/stackdriver-cloudtrace-utils.ts
  packages/opencensus-exporter-stackdriver/test/test-stackdriver-cloudtrace-utils.ts
Labels: cla: yes

#473 Add support for Opencensus Span links to Thrift Span references
  CHANGELOG.md
  packages/opencensus-exporter-jaeger/src/jaeger-driver/index.ts
  packages/opencensus-exporter-jaeger/test/test-jaeger.ts
Labels: cla: yes

#471 add redis instrumentation plugins by default
  README.md
  packages/opencensus-instrumentation-all/package-lock.json
  packages/opencensus-instrumentation-all/package.json
  packages/opencensus-instrumentation-all/src/index.js
  packages/opencensus-nodejs/README.md
Labels: cla: yes

#478 chore(multiple): 0.0.11 release proposal
  lerna.json
  packages/opencensus-core/package.json
  packages/opencensus-example-automatic-tracing/package.json
  packages/opencensus-exporter-instana/package.json
  packages/opencensus-exporter-jaeger/package-lock.json
  packages/opencensus-exporter-jaeger/package.json
  packages/opencensus-exporter-ocagent/package-lock.json
  packages/opencensus-exporter-ocagent/package.json
  packages/opencensus-exporter-prometheus/package-lock.json
  packages/opencensus-exporter-prometheus/package.json
  packages/opencensus-exporter-stackdriver/package-lock.json
  packages/opencensus-exporter-stackdriver/package.json
  packages/opencensus-exporter-zipkin/package.json
  packages/opencensus-exporter-zpages/package.json
  packages/opencensus-instrumentation-all/package.json
  packages/opencensus-instrumentation-grpc/package-lock.json
  packages/opencensus-instrumentation-grpc/package.json
  packages/opencensus-instrumentation-http/package-lock.json
  packages/opencensus-instrumentation-http/package.json
  packages/opencensus-instrumentation-http2/package-lock.json
  packages/opencensus-instrumentation-http2/package.json
  packages/opencensus-instrumentation-https/package-lock.json
  packages/opencensus-instrumentation-https/package.json
  packages/opencensus-instrumentation-ioredis/package.json
  packages/opencensus-instrumentation-mongodb/package-lock.json
  packages/opencensus-instrumentation-mongodb/package.json
  packages/opencensus-instrumentation-redis/package.json
  packages/opencensus-nodejs/package.json
  packages/opencensus-propagation-b3/package-lock.json
  packages/opencensus-propagation-b3/package.json
  packages/opencensus-propagation-binaryformat/package.json
  packages/opencensus-propagation-jaeger/package-lock.json
  packages/opencensus-propagation-jaeger/package.json
  packages/opencensus-propagation-stackdriver/package.json
  packages/opencensus-propagation-tracecontext/package-lock.json
  packages/opencensus-propagation-tracecontext/package.json
  packages/opencensus-resource-util/package-lock.json
  packages/opencensus-resource-util/package.json
Labels: cla: yes

#479 Post Release: update CHANGELOG and Examples
  CHANGELOG.md
  examples/grpc/package.json
  examples/http/package.json
  examples/stats/exporter/package.json
  examples/stats/web_client_monitoring/package.json
  packages/opencensus-exporter-prometheus/src/prometheus-stats.ts
Labels: cla: yes

#441 Consolidating Span and RootSpan to allow Spans to recursively have children
  packages/opencensus-core/src/exporters/console-exporter.ts
  packages/opencensus-core/src/exporters/exporter-buffer.ts
  packages/opencensus-core/src/exporters/types.ts
  packages/opencensus-core/src/trace/model/no-record/no-record-root-span.ts
  packages/opencensus-core/src/trace/model/no-record/no-record-span-base.ts
  packages/opencensus-core/src/trace/model/no-record/no-record-span.ts
  packages/opencensus-core/src/trace/model/root-span.ts
  packages/opencensus-core/src/trace/model/span-base.ts
  packages/opencensus-core/src/trace/model/span.ts
  packages/opencensus-core/src/trace/model/tracer.ts
  packages/opencensus-core/src/trace/model/types.ts
  packages/opencensus-core/test/test-root-span.ts
  packages/opencensus-core/test/test-tracer.ts
  packages/opencensus-exporter-instana/src/instana.ts
  packages/opencensus-exporter-instana/test/test-instana.ts
  packages/opencensus-exporter-jaeger/src/jaeger.ts
  packages/opencensus-exporter-ocagent/src/adapters.ts
  packages/opencensus-exporter-ocagent/src/ocagent.ts
  packages/opencensus-exporter-ocagent/test/test-ocagent.ts
  packages/opencensus-exporter-stackdriver/src/stackdriver-cloudtrace.ts
  packages/opencensus-exporter-stackdriver/test/test-stackdriver-cloudtrace.ts
  packages/opencensus-exporter-zipkin/src/zipkin.ts
  packages/opencensus-exporter-zipkin/test/test-zipkin.ts
  packages/opencensus-exporter-zpages/src/zpages-frontend/page-handlers/tracez.page-handler.ts
  packages/opencensus-exporter-zpages/src/zpages.ts
  packages/opencensus-exporter-zpages/test/test-zpages.ts
  packages/opencensus-instrumentation-grpc/src/grpc.ts
  packages/opencensus-instrumentation-grpc/test/test-grpc.ts
  packages/opencensus-instrumentation-http/test/test-http.ts
  packages/opencensus-instrumentation-http2/test/test-http2.ts
  packages/opencensus-instrumentation-https/test/test-https.ts
  packages/opencensus-instrumentation-ioredis/test/test-ioredis.ts
  packages/opencensus-instrumentation-mongodb/test/test-mongodb.ts
  packages/opencensus-instrumentation-redis/test/test-redis.ts
Labels: cla: yes

#482 http-instrumentation: fix propagation errors when using Expect header #481
  packages/opencensus-instrumentation-http/src/http.ts
  packages/opencensus-instrumentation-http/test/test-http.ts
Labels: cla: yes

#469 Derived Gauge: Add support for extracting value from a function
  examples/gauge/derived-gauge-quickstart.js
  packages/opencensus-core/src/metrics/gauges/derived-gauge.ts
  packages/opencensus-core/test/test-derived-gauge.ts
Labels: cla: yes
