Repository census-instrumentation/opencensus-node, pull requests merged in 2019-03, with the labels that each got.

#375 chore: add node 11 ci job
  .circleci/config.yml
Labels: cla: yes

#370 Add support for recording HTTP stats
  CHANGELOG.md
  packages/opencensus-instrumentation-grpc/src/index.ts
  packages/opencensus-instrumentation-http/src/http-stats.ts
  packages/opencensus-instrumentation-http/src/http.ts
  packages/opencensus-instrumentation-http/src/index.ts
  packages/opencensus-instrumentation-http/test/test-http.ts
  packages/opencensus-instrumentation-http/tsconfig.json
Labels: cla: yes

#378 Update README and CHANGELOG
  CHANGELOG.md
  README.md
  packages/opencensus-core/test/test-stats.ts
  packages/opencensus-example-automatic-tracing/README.md
  packages/opencensus-exporter-instana/README.md
  packages/opencensus-exporter-jaeger/README.md
  packages/opencensus-exporter-ocagent/README.md
  packages/opencensus-exporter-stackdriver/README.md
  packages/opencensus-exporter-zpages/README.md
  packages/opencensus-nodejs/README.md
Labels: cla: yes

#380 Exporter/Stackdriver: Update childSpanCount
  packages/opencensus-exporter-stackdriver/src/stackdriver-cloudtrace.ts
  packages/opencensus-exporter-stackdriver/test/test-stackdriver-cloudtrace.ts
Labels: GA-Effort, cla: yes, exporters, traces

#359 implement redis instrumentation plugin
  .circleci/config.yml
  packages/opencensus-instrumentation-redis/.npmignore
  packages/opencensus-instrumentation-redis/AUTHORS
  packages/opencensus-instrumentation-redis/LICENSE
  packages/opencensus-instrumentation-redis/README.md
  packages/opencensus-instrumentation-redis/codecov.yml
  packages/opencensus-instrumentation-redis/package-lock.json
  packages/opencensus-instrumentation-redis/package.json
  packages/opencensus-instrumentation-redis/src/index.ts
  packages/opencensus-instrumentation-redis/src/redis.ts
  packages/opencensus-instrumentation-redis/test/test-redis.ts
  packages/opencensus-instrumentation-redis/tsconfig.json
Labels: cla: yes

#379 Add example for tracing
  examples/trace/multi-span-tracing.js
  examples/trace/multi-span-tracing_ui.png
Labels: cla: yes

#381 Exporter/Zipkin: Enforce strictNullChecks and noUnusedLocals
  CHANGELOG.md
  packages/opencensus-exporter-zipkin/README.md
  packages/opencensus-exporter-zipkin/src/zipkin.ts
  packages/opencensus-exporter-zipkin/test/test-zipkin.ts
  packages/opencensus-exporter-zipkin/tsconfig.json
Labels: GA-Effort, cla: yes

#358 Fix mongodb instrumentation not ending span correctly
  packages/opencensus-instrumentation-mongodb/package-lock.json
  packages/opencensus-instrumentation-mongodb/src/mongodb.ts
  packages/opencensus-instrumentation-mongodb/test/test-mongodb.ts
Labels: cla: yes

#389 Add a NoRecord RootSpan and Span
  CHANGELOG.md
  packages/opencensus-core/src/trace/model/no-record/no-record-root-span.ts
  packages/opencensus-core/src/trace/model/no-record/no-record-span-base.ts
  packages/opencensus-core/src/trace/model/no-record/no-record-span.ts
  packages/opencensus-core/src/trace/model/tracer.ts
  packages/opencensus-core/test/test-no-record-root-span.ts
  packages/opencensus-core/test/test-no-record-span.ts
  packages/opencensus-core/test/test-tracer.ts
Labels: cla: yes

#396 Fix Build : "Cannot find name 'Exclude"
  packages/opencensus-instrumentation-grpc/package-lock.json
  packages/opencensus-instrumentation-grpc/package.json
Labels: cla: yes

#377 Propagation/TraceContext: Enforce strictNullChecks and noUnusedLocals
  packages/opencensus-propagation-tracecontext/src/tracecontext-format.ts
  packages/opencensus-propagation-tracecontext/test/test-tracecontext-format.ts
  packages/opencensus-propagation-tracecontext/tsconfig.json
Labels: GA-Effort, cla: yes

#398 Fix vulnerability : handlebars
  package-lock.json
Labels: cla: yes

#397 Add support for unregister stats exporter whenever the exporter is no…
  CHANGELOG.md
  packages/opencensus-core/src/exporters/console-exporter.ts
  packages/opencensus-core/src/exporters/types.ts
  packages/opencensus-core/src/stats/stats.ts
  packages/opencensus-core/src/stats/types.ts
  packages/opencensus-core/test/test-stats.ts
  packages/opencensus-exporter-prometheus/src/prometheus-stats.ts
  packages/opencensus-exporter-stackdriver/src/stackdriver-monitoring.ts
  packages/opencensus-exporter-stackdriver/test/test-stackdriver-monitoring.ts
  packages/opencensus-exporter-zpages/src/zpages.ts
  packages/opencensus-instrumentation-grpc/test/test-grpc.ts
  packages/opencensus-instrumentation-http/test/test-http.ts
Labels: cla: yes

#390 Exporter/Instana: Enforce strictNullChecks and noUnusedLocals
  CHANGELOG.md
  packages/opencensus-exporter-instana/README.md
  packages/opencensus-exporter-instana/src/instana.ts
  packages/opencensus-exporter-instana/test/test-instana.ts
  packages/opencensus-exporter-instana/tsconfig.json
Labels: cla: yes

#401 Upgrade grpc to 1.19
  packages/opencensus-instrumentation-grpc/package-lock.json
  packages/opencensus-instrumentation-grpc/package.json
  packages/opencensus-instrumentation-grpc/tsconfig.json
Labels: cla: yes

#394 Add support for overriding sampling per span
  CHANGELOG.md
  packages/opencensus-core/src/trace/model/no-record/no-record-root-span.ts
  packages/opencensus-core/src/trace/model/root-span.ts
  packages/opencensus-core/src/trace/model/tracer.ts
  packages/opencensus-core/src/trace/model/types.ts
  packages/opencensus-core/test/test-console-exporter.ts
  packages/opencensus-core/test/test-exporter-buffer.ts
  packages/opencensus-core/test/test-no-record-root-span.ts
  packages/opencensus-core/test/test-no-record-span.ts
  packages/opencensus-core/test/test-root-span.ts
  packages/opencensus-core/test/test-sampler.ts
  packages/opencensus-core/test/test-span.ts
  packages/opencensus-core/test/test-tracer.ts
Labels: cla: yes

#382 Exporter/jaeger: Enforce strictNullChecks and noUnusedLocals
  CHANGELOG.md
  packages/opencensus-exporter-jaeger/README.md
  packages/opencensus-exporter-jaeger/src/jaeger-driver/index.ts
  packages/opencensus-exporter-jaeger/src/jaeger.ts
  packages/opencensus-exporter-jaeger/test/test-jaeger.ts
  packages/opencensus-exporter-jaeger/tsconfig.json
Labels: cla: yes

#403 Code Enhancement/Refactor
  packages/opencensus-core/src/trace/model/no-record/no-record-root-span.ts
  packages/opencensus-core/src/trace/model/root-span.ts
  packages/opencensus-core/src/trace/model/tracer.ts
  packages/opencensus-core/src/trace/model/types.ts
  packages/opencensus-core/test/test-console-exporter.ts
  packages/opencensus-core/test/test-tracer.ts
  packages/opencensus-nodejs/src/trace/instrumentation/plugin-loader.ts
  packages/opencensus-nodejs/src/trace/tracing.ts
  packages/opencensus-nodejs/test/test-plugin-loader.ts
  packages/opencensus-nodejs/test/test-tracing.ts
  packages/opencensus-nodejs/tsconfig.json
Labels: cla: yes, code health, enhancement

#302 Jaeger exporter: remove require wrapper and make requires direct
  packages/opencensus-exporter-jaeger/src/jaeger-driver/index.ts
Labels: cla: yes

#406 Instrumentation/HTTP2/HTTPS: Enforce strictNullChecks and noUnusedLocals
  packages/opencensus-instrumentation-http2/src/http2.ts
  packages/opencensus-instrumentation-http2/test/test-http2.ts
  packages/opencensus-instrumentation-http2/tsconfig.json
  packages/opencensus-instrumentation-https/src/https.ts
  packages/opencensus-instrumentation-https/test/test-https.ts
  packages/opencensus-instrumentation-https/tsconfig.json
Labels: cla: yes, code health, enhancement, plugin

#409 Restrict people who can approve reviews. This is to ensure code quality.
  .github/CODEOWNERS
Labels: cla: yes

#405 Add support for recording exemplars
  CHANGELOG.md
  packages/opencensus-core/src/stats/recorder.ts
  packages/opencensus-core/src/stats/stats.ts
  packages/opencensus-core/src/stats/types.ts
  packages/opencensus-core/src/stats/view.ts
  packages/opencensus-core/test/test-recorder.ts
  packages/opencensus-core/test/test-view.ts
Labels: Metrics, cla: yes, feature-request

#411 Bump protobufjs to 6.x
  package-lock.json
  packages/opencensus-instrumentation-grpc/package-lock.json
  packages/opencensus-instrumentation-grpc/package.json
  packages/opencensus-instrumentation-grpc/tsconfig.json
Labels: cla: yes

#412 Enforce/strictNullChecks: MongoDB Plugin
  packages/opencensus-instrumentation-mongodb/src/mongodb.ts
  packages/opencensus-instrumentation-mongodb/test/test-mongodb.ts
  packages/opencensus-instrumentation-mongodb/tsconfig.json
Labels: cla: yes

#407 Add default labels for ISSUE_TEMPLATE
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: cla: yes

#408 Exporter/Stackdriver: Enforce strictNullChecks and noUnusedLocals
  packages/opencensus-exporter-stackdriver/src/stackdriver-cloudtrace-utils.ts
  packages/opencensus-exporter-stackdriver/src/stackdriver-cloudtrace.ts
  packages/opencensus-exporter-stackdriver/src/stackdriver-monitoring-utils.ts
  packages/opencensus-exporter-stackdriver/src/stackdriver-monitoring.ts
  packages/opencensus-exporter-stackdriver/test/test-stackdriver-cloudtrace-utils.ts
  packages/opencensus-exporter-stackdriver/test/test-stackdriver-cloudtrace.ts
  packages/opencensus-exporter-stackdriver/test/test-stackdriver-monitoring-utils.ts
  packages/opencensus-exporter-stackdriver/test/test-stackdriver-monitoring.ts
  packages/opencensus-exporter-stackdriver/tsconfig.json
Labels: cla: yes

#420 Add snyk (vulnerability) badge
  README.md
Labels: cla: yes, code health

#419 Exporter/Prometheus: Enforce strictNullChecks and noUnusedLocals
  examples/stats/exporter/prometheus.js
  package-lock.json
  packages/opencensus-core/src/stats/types.ts
  packages/opencensus-core/src/stats/view.ts
  packages/opencensus-exporter-prometheus/README.md
  packages/opencensus-exporter-prometheus/src/prometheus-stats.ts
  packages/opencensus-exporter-prometheus/test/test-prometheus-stats.ts
  packages/opencensus-exporter-prometheus/tsconfig.json
Labels: cla: yes

#417 Use options.host instead of options.hostname (#416)
  packages/opencensus-instrumentation-http/src/http.ts
Labels: cla: yes, plugin, traces

#410 add ioredis instrumentation plugin
  packages/opencensus-instrumentation-ioredis/.npmignore
  packages/opencensus-instrumentation-ioredis/AUTHORS
  packages/opencensus-instrumentation-ioredis/LICENSE
  packages/opencensus-instrumentation-ioredis/README.md
  packages/opencensus-instrumentation-ioredis/codecov.yml
  packages/opencensus-instrumentation-ioredis/package-lock.json
  packages/opencensus-instrumentation-ioredis/package.json
  packages/opencensus-instrumentation-ioredis/src/index.ts
  packages/opencensus-instrumentation-ioredis/src/ioredis.ts
  packages/opencensus-instrumentation-ioredis/test/test-ioredis.ts
  packages/opencensus-instrumentation-ioredis/tsconfig.json
Labels: cla: yes, plugin

#426 opencensus-nodejs: Enforce strictNullChecks
  packages/opencensus-nodejs/src/trace/tracing.ts
  packages/opencensus-nodejs/test/test-tracing.ts
  packages/opencensus-nodejs/tsconfig.json
Labels: cla: yes

#421 Propagation/B3: Enforce strictNullChecks and noUnusedLocals
  packages/opencensus-propagation-b3/src/b3-format.ts
  packages/opencensus-propagation-b3/src/validators.ts
  packages/opencensus-propagation-b3/test/test-b3-format.ts
  packages/opencensus-propagation-b3/tsconfig.json
Labels: GA-Effort, cla: yes, enhancement

#418 Stats: Record against implicit (current) tag context
  examples/tags/tag-context-example.js
  packages/opencensus-core/src/index.ts
  packages/opencensus-core/src/internal/cls-ah.ts
  packages/opencensus-core/src/stats/stats.ts
  packages/opencensus-core/src/tags/tag-map.ts
  packages/opencensus-core/src/tags/tagger.ts
  packages/opencensus-core/test/test-stats.ts
  packages/opencensus-core/test/test-tagger.ts
Labels: GA-Effort, Stats, WIP, cla: yes, tags

#424 Tags: Add support for TagMetadata
  CHANGELOG.md
  packages/opencensus-core/src/exporters/console-exporter.ts
  packages/opencensus-core/src/exporters/types.ts
  packages/opencensus-core/src/index.ts
  packages/opencensus-core/src/tags/tag-map.ts
  packages/opencensus-core/src/tags/types.ts
  packages/opencensus-core/test/test-recorder.ts
  packages/opencensus-core/test/test-tag-map.ts
  packages/opencensus-instrumentation-grpc/src/grpc.ts
  packages/opencensus-instrumentation-http/src/http.ts
Labels: API, cla: yes, tags

#432 opencensus-zpages: Enforce strictNullChecks and noUnusedLocals
  packages/opencensus-exporter-zpages/src/zpages-frontend/latency-bucket-boundaries.ts
  packages/opencensus-exporter-zpages/src/zpages-frontend/page-handlers/rpcz.page-handler.ts
  packages/opencensus-exporter-zpages/src/zpages-frontend/page-handlers/statsz.page-handler.ts
  packages/opencensus-exporter-zpages/src/zpages-frontend/page-handlers/traceconfigz.page-handler.ts
  packages/opencensus-exporter-zpages/src/zpages-frontend/page-handlers/tracez.page-handler.ts
  packages/opencensus-exporter-zpages/src/zpages.ts
  packages/opencensus-exporter-zpages/test/test-zpages.ts
  packages/opencensus-exporter-zpages/tsconfig.json
Labels: cla: yes

#438 Remove deprecated @types/pkg-dir and pkg-dir
  packages/opencensus-exporter-zpages/package-lock.json
  packages/opencensus-exporter-zpages/package.json
  packages/opencensus-exporter-zpages/src/zpages-frontend/page-handlers/rpcz.page-handler.ts
  packages/opencensus-exporter-zpages/src/zpages-frontend/page-handlers/statsz.page-handler.ts
  packages/opencensus-exporter-zpages/src/zpages-frontend/page-handlers/traceconfigz.page-handler.ts
  packages/opencensus-exporter-zpages/src/zpages-frontend/page-handlers/tracez.page-handler.ts
Labels: cla: yes

#436 Make Stackdriver propagation module consistent with other propagations interface
  packages/opencensus-propagation-stackdriver/package.json
  packages/opencensus-propagation-stackdriver/src/index.ts
  packages/opencensus-propagation-stackdriver/src/stackdriver-format.ts
  packages/opencensus-propagation-stackdriver/src/v1.ts
  packages/opencensus-propagation-stackdriver/test/test-stackdriver-format.ts
  packages/opencensus-propagation-stackdriver/test/test-v1.ts
  packages/opencensus-propagation-stackdriver/tsconfig.json
Labels: cla: yes, code health, enhancement

#431 Add support for Binary Format serializer for TagMap
  packages/opencensus-core/src/tags/propagation/binary-serializer.ts
  packages/opencensus-core/src/tags/propagation/variant-encoding.ts
  packages/opencensus-core/test/test-binary-serializer.ts
  packages/opencensus-core/test/test-variant-encoding.ts
Labels: cla: yes

#435 only require userland CLS when needed
  packages/opencensus-core/src/internal/cls.ts
Labels: cla: yes

#433 Propagation-Jaeger: Enforce strictNullChecks and noUnusedLocals
  packages/opencensus-propagation-jaeger/README.md
  packages/opencensus-propagation-jaeger/src/jaeger-format.ts
  packages/opencensus-propagation-jaeger/src/validators.ts
  packages/opencensus-propagation-jaeger/test/test-jaeger-format.ts
  packages/opencensus-propagation-jaeger/tsconfig.json
Labels: cla: yes, code health

#439 Chore: Remove unwanted dependencies
  packages/opencensus-core/package.json
  packages/opencensus-exporter-instana/package.json
  packages/opencensus-exporter-jaeger/package.json
  packages/opencensus-exporter-ocagent/package.json
  packages/opencensus-exporter-prometheus/package.json
  packages/opencensus-exporter-stackdriver/package.json
  packages/opencensus-exporter-zipkin/package.json
  packages/opencensus-instrumentation-grpc/package.json
  packages/opencensus-instrumentation-http/package.json
  packages/opencensus-instrumentation-http2/package.json
  packages/opencensus-instrumentation-https/package.json
  packages/opencensus-instrumentation-ioredis/package.json
  packages/opencensus-instrumentation-mongodb/package.json
  packages/opencensus-instrumentation-redis/package.json
  packages/opencensus-nodejs/package.json
  packages/opencensus-propagation-b3/package.json
  packages/opencensus-propagation-binaryformat/package.json
  packages/opencensus-propagation-jaeger/package.json
  packages/opencensus-propagation-stackdriver/package.json
  packages/opencensus-propagation-tracecontext/package.json
Labels: cla: yes

#440 Chore: sync package-lock
  packages/opencensus-core/package-lock.json
  packages/opencensus-exporter-instana/package-lock.json
  packages/opencensus-exporter-jaeger/package-lock.json
  packages/opencensus-exporter-ocagent/package-lock.json
  packages/opencensus-exporter-prometheus/package-lock.json
  packages/opencensus-exporter-stackdriver/package-lock.json
  packages/opencensus-exporter-zipkin/package-lock.json
  packages/opencensus-instrumentation-grpc/package-lock.json
  packages/opencensus-instrumentation-http/package-lock.json
  packages/opencensus-instrumentation-http2/package-lock.json
  packages/opencensus-instrumentation-https/package-lock.json
  packages/opencensus-instrumentation-ioredis/package-lock.json
  packages/opencensus-instrumentation-mongodb/package-lock.json
  packages/opencensus-instrumentation-redis/package-lock.json
  packages/opencensus-nodejs/package-lock.json
  packages/opencensus-propagation-b3/package-lock.json
  packages/opencensus-propagation-binaryformat/package-lock.json
  packages/opencensus-propagation-jaeger/package-lock.json
  packages/opencensus-propagation-stackdriver/package-lock.json
  packages/opencensus-propagation-tracecontext/package-lock.json
Labels: cla: yes

#445 Add HTTP/W3C text format serializer to Tag propagation component
  CHANGELOG.md
  packages/opencensus-core/src/index.ts
  packages/opencensus-core/src/tags/propagation/text-format.ts
  packages/opencensus-core/test/test-text-format.ts
Labels: cla: yes

#443 Add support for gRPC tags propagation
  examples/tags/tag-context-example.js
  packages/opencensus-core/src/index.ts
  packages/opencensus-core/src/internal/cls-ah.ts
  packages/opencensus-core/src/internal/cls.ts
  packages/opencensus-core/src/stats/stats.ts
  packages/opencensus-core/src/stats/types.ts
  packages/opencensus-core/src/tags/tagger.ts
  packages/opencensus-core/src/trace/model/tracer.ts
  packages/opencensus-core/test/test-stats.ts
  packages/opencensus-core/test/test-tagger.ts
  packages/opencensus-instrumentation-grpc/src/grpc.ts
  packages/opencensus-instrumentation-grpc/test/test-grpc.ts
Labels: cla: yes

#444 Use ts-mocha to run tests
  .circleci/config.yml
  packages/opencensus-core/package-lock.json
  packages/opencensus-core/package.json
  packages/opencensus-core/src/common/version.ts
  packages/opencensus-exporter-instana/package-lock.json
  packages/opencensus-exporter-instana/package.json
  packages/opencensus-exporter-jaeger/package-lock.json
  packages/opencensus-exporter-jaeger/package.json
  packages/opencensus-exporter-jaeger/src/jaeger.ts
  packages/opencensus-exporter-prometheus/package-lock.json
  packages/opencensus-exporter-prometheus/package.json
  packages/opencensus-exporter-stackdriver/package-lock.json
  packages/opencensus-exporter-stackdriver/package.json
  packages/opencensus-exporter-zipkin/package-lock.json
  packages/opencensus-exporter-zipkin/package.json
  packages/opencensus-exporter-zpages/package-lock.json
  packages/opencensus-exporter-zpages/package.json
  packages/opencensus-exporter-zpages/src/zpages-frontend/page-handlers/rpcz.page-handler.ts
  packages/opencensus-exporter-zpages/src/zpages-frontend/page-handlers/statsz.page-handler.ts
  packages/opencensus-exporter-zpages/src/zpages-frontend/page-handlers/templates-dir.ts
  packages/opencensus-exporter-zpages/src/zpages-frontend/page-handlers/traceconfigz.page-handler.ts
  packages/opencensus-exporter-zpages/src/zpages-frontend/page-handlers/tracez.page-handler.ts
  packages/opencensus-instrumentation-grpc/package-lock.json
  packages/opencensus-instrumentation-grpc/package.json
  packages/opencensus-instrumentation-http/package-lock.json
  packages/opencensus-instrumentation-http/package.json
  packages/opencensus-instrumentation-http2/package-lock.json
  packages/opencensus-instrumentation-http2/package.json
  packages/opencensus-instrumentation-https/package-lock.json
  packages/opencensus-instrumentation-https/package.json
  packages/opencensus-instrumentation-ioredis/package-lock.json
  packages/opencensus-instrumentation-ioredis/package.json
  packages/opencensus-instrumentation-mongodb/package-lock.json
  packages/opencensus-instrumentation-mongodb/package.json
  packages/opencensus-propagation-b3/package-lock.json
  packages/opencensus-propagation-b3/package.json
  packages/opencensus-propagation-binaryformat/package-lock.json
  packages/opencensus-propagation-binaryformat/package.json
  packages/opencensus-propagation-jaeger/package-lock.json
  packages/opencensus-propagation-jaeger/package.json
  packages/opencensus-propagation-stackdriver/package-lock.json
  packages/opencensus-propagation-stackdriver/package.json
  packages/opencensus-propagation-tracecontext/package-lock.json
  packages/opencensus-propagation-tracecontext/package.json
  packages/opencensus-resource-util/package-lock.json
  packages/opencensus-resource-util/package.json
Labels: cla: yes, enhancement, review

#448 Add code style checker in unit test workflow
  .circleci/config.yml
  package.json
Labels: cla: yes

#451 Exclude JS files from codecov
  packages/opencensus-core/package.json
  packages/opencensus-exporter-instana/package.json
  packages/opencensus-exporter-jaeger/package.json
  packages/opencensus-exporter-prometheus/package.json
  packages/opencensus-exporter-stackdriver/package.json
  packages/opencensus-exporter-zipkin/package.json
  packages/opencensus-exporter-zpages/package.json
  packages/opencensus-instrumentation-grpc/package.json
  packages/opencensus-instrumentation-http/package.json
  packages/opencensus-instrumentation-http2/package.json
  packages/opencensus-instrumentation-https/package.json
  packages/opencensus-instrumentation-ioredis/package.json
  packages/opencensus-instrumentation-mongodb/package.json
  packages/opencensus-propagation-b3/package.json
  packages/opencensus-propagation-binaryformat/package.json
  packages/opencensus-propagation-jaeger/package.json
  packages/opencensus-propagation-tracecontext/package.json
  packages/opencensus-resource-util/package.json
Labels: cla: yes

#456 Regenerate ocagent proto files
  packages/opencensus-exporter-ocagent/src/protos/opencensus/proto/agent/common/v1/common.proto
  packages/opencensus-exporter-ocagent/src/protos/opencensus/proto/agent/trace/v1/trace_service.proto
  packages/opencensus-exporter-ocagent/src/protos/opencensus/proto/resource/v1/resource.proto
  packages/opencensus-exporter-ocagent/src/protos/opencensus/proto/trace/v1/trace.proto
  packages/opencensus-exporter-ocagent/src/protos/opencensus/proto/trace/v1/trace_config.proto
Labels: cla: yes
